/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *\
 *     __   __)  __     __)     _                                                    *
 *    (, ) /    (, /   /    ___/__)                                                  *
 *      /(        /   /    (, /    _     _ _   _ __                                  *
 *   ) /  \_  o  /   /    o  /   _(/_(_(_(/___(/_/ (_                                *
 *  (_/     JJJJ(___(_J     (_____CCCCCCCCHHHHHHHHH     HHHHHHHHHRRRRRRRRRRRRRRRRR   *
 *         J:::::::::J   CCC::::::::::::CH:::::::H     H:::::::HR::::::::::::::::R   *
 *         J:::::::::J CC:::::::::::::::CH:::::::H     H:::::::HR::::::RRRRRR:::::R  *
 *         JJ:::::::JJC:::::CCCCCCCC::::CHH::::::H     H::::::HHRR:::::R     R:::::R *
 *           J:::::J C:::::C       CCCCCC  H:::::H     H:::::H    R::::R     R:::::R *
 *           J:::::JC:::::C                H:::::H     H:::::H    R::::R     R:::::R *
 *           J:::::JC:::::C                H::::::HHHHH::::::H    R::::RRRRRR:::::R  *
 *           J:::::JC:::::C                H:::::::::::::::::H    R:::::::::::::RR   *
             J:::::JC:::::C                H:::::::::::::::::H    R::::RRRRRR:::::R  *
 JJJJJJJ     J:::::JC:::::C                H::::::HHHHH::::::H    R::::R     R:::::R *
 J:::::J     J:::::JC:::::C                H:::::H     H:::::H    R::::R     R:::::R *
 J::::::J   J::::::J C:::::C       CCCCCC  H:::::H     H:::::H    R::::R     R:::::R *
 J:::::::JJJ:::::::J  C:::::CCCCCCCC::::CHH::::::H     H::::::HHRR:::::R     R:::::R *
  JJ:::::::::::::JJ    CC:::::::::::::::CH:::::::H     H:::::::HR::::::R     R:::::R *
    JJ:::::::::JJ        CCC::::::::::::CH:::::::H     H:::::::HR::::::R     R:::::R *
 *    JJJJJJJJJ             CCCCCCCCCCCCCHHHHHHHHH     HHHHHHHHHRRRRRRRR     RRRRRRR *
 *                                                                                   *
 * This file was generated by the K.U.Leuven JCHR System v1.6.0                      *
 * (available at http://www.cs.kuleuven.be/~petervw/JCHR/).                          *
 *                                                                                   *
 * Do not edit: edit the jchr-source file instead.                                   *
\* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

package runtime.history;

import runtime.history.TuplePropagationHistory;

/* @javax.annotation.Generated(
	value = "The K.U.Leuven JCHR System v1.6.0",
	date = "2008-03-10T10:38:16.896+01:00",
	comments = "http://www.cs.kuleuven.be/~petervw/JCHR/") */
public final class Tuple3 extends TuplePropagationHistory.Tuple {
	private final int X1;
	private final int X2;
	private final int X3;

	public Tuple3(int X1, int X2, int X3) {
		this.X1 = X1;
		this.X2 = X2;
		this.X3 = X3;
		int hash = 37 * (37 * (37 * (23) + X1) + X2) + X3;
		hash ^= (hash >>> 20) ^ (hash >>> 12);
		this.hash = hash ^ (hash >>> 7) ^ (hash >>> 4);
	}

	/**
	 * {@inheritDoc}
	 *
	 * @pre other instanceof Tuple3
	 */
	@Override
	public boolean equals(Object other) {
		return (this.X1 == ((Tuple3)other).X1)
		    && (this.X2 == ((Tuple3)other).X2)
		    && (this.X3 == ((Tuple3)other).X3);
	}

	public boolean equals(Tuple3 other) {
		return (this.X1 == other.X1)
		    && (this.X2 == other.X2)
		    && (this.X3 == other.X3);
	}

	@Override
	public String toString() {
		final StringBuilder result = new StringBuilder(48);
		result.append('(');
		result.append(X1);
		result.append(", ");
		result.append(X2);
		result.append(", ");
		result.append(X3);
		result.append(')');
		return result.toString();
	}
}
